ALLOWED_UPLOAD_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
IMAGE_UPLOAD_FOLDER='uploads'
IMAGE_UPLOAD_SIZE_LIMIT=20000000
VISION_BUCKET_NAME="art-images-test"
IMAGE_THUMB_FOLDER='thumbs'
TEST_PRODUCT_ID='veggies'
DEV_PRODUCT_ID='socks'
MAIN_PRODUCT_ID='schmiede'