ALLOWED_UPLOAD_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
IMAGE_UPLOAD_FOLDER='uploads'
IMAGE_UPLOAD_SIZE_LIMIT=20000000
VISION_BUCKET_NAME="art-images-test"
IMAGE_THUMB_FOLDER='thumbs'
TEST_PRODUCT_IDS=['veggies']
DEV_PRODUCT_IDS=['socks']
MAIN_PRODUCT_IDS=['schmiede23','blood']