version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:80"
    environment:
      - FLASK_ENV=production
      - GOOGLE_CREDENTIAL_PATH=${GOOGLE_CREDENTIAL_ONLY_PATH}${GOOGLE_CREDENTIAL_FILE}
    env_file:
      - .env
    depends_on:
      - database
      - ipfs


  ipfs:
    image: ipfs/go-ipfs:v0.22.0
    container_name: ipfs_service
    ports:
      - "4001:4001"  # swarm
      - "5001:5001"  # API
      - "8080:8080"  # Gateway
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_staging:/export


  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        - REACT_APP_DEVELOPMENT_MODE=production
        - REACT_APP_DOCKERIZED=dockerized
    # environment:
    #   - REACT_APP_DEVELOPMENT_MODE=development
    #   - REACT_APP_DOCKERIZED=dockerized
    # volumes:
    #   - ./frontend/dist:/usr/local/apache2/htdocs/
    ports:
      - "80:80"
    depends_on:
      - backend
      - database
  
  database:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    env_file:
    - .env
    volumes:
      - pgdata2:/var/lib/postgresql/data
      # - ./path/to/your/sqldump:/docker-entrypoint-initdb.d/dump.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: client
    ports:
      - "8881:80"
    env_file:
    - .env
    depends_on:
      - database

volumes:
  pgdata2:
  ipfs_data:
  ipfs_staging: